<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastArticles()
    {
        $qb = $this->createQueryBuilder('n');
        $qb ->where('n.publicationDate <= :now')
            ->setParameter('now', new \DateTime('now'))
            ->orderBy('n.publicationDate', 'DESC')
            ->setMaxResults(5);
        return $qb->getQuery()
                   ->getResult();
    }
}
