<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbComments($id)
    {
        return $this->createQueryBuilder('m')
            ->createQuery('SELECT COUNT(m) FROM AppBundle:Comment m WHERE m.article = :id')
            ->setParameter(':id', $id)
            ->getSingleScalarResult();
    }
}
