# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$.m5X6rRqpDi3c3SfG7wL7.AKyOb0fOmy8WGzKzzXJAjYG8rpWH73C
                        roles: 'ROLE_ADMIN'

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/administration, roles: ROLE_ADMIN }
