# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.article_search_service:
        class: AppBundle\Services\ArticleSearchService
        arguments: ['@doctrine']
